#!/usr/bin/env python3
"""
start_services.py

Bootstraps and starts the Self-hosted AI Package services.
Refactored for robustness, cross-platform compatibility, and clean code.
"""

import os
import subprocess
import shutil
import time
import argparse
import sys
import logging
import secrets
from pathlib import Path
from typing import Dict, List, Optional

try:
    from dotenv import load_dotenv, set_key
except ImportError:
    load_dotenv = None
    set_key = None

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def run_command(cmd: List[str], cwd: Optional[str] = None):
    """Run a shell command and log it."""
    logger.info(f"Running: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, cwd=cwd, check=True)
    except subprocess.CalledProcessError as e:
        logger.error(f"Command failed with exit code {e.returncode}: {' '.join(cmd)}")
        raise

def clone_supabase_repo():
    """Clone the Supabase repository using sparse checkout if not already present."""
    supabase_dir = Path("supabase")
    if not supabase_dir.exists():
        logger.info("Cloning the Supabase repository...")
        run_command([
            "git", "clone", "--filter=blob:none", "--no-checkout",
            "https://github.com/supabase/supabase.git"
        ])
        run_command(["git", "-C", "supabase", "sparse-checkout", "init", "--cone"])
        run_command(["git", "-C", "supabase", "sparse-checkout", "set", "docker"])
        run_command(["git", "-C", "supabase", "checkout", "master"])
    else:
        if (supabase_dir / ".git").exists():
            logger.info("Supabase repository already exists, updating...")
            run_command(["git", "-C", "supabase", "pull"])
        else:
            logger.info("Supabase directory exists and is fully integrated (no .git folder). Skipping update.")

def prepare_supabase_env():
    """Merge root .env with supabase/docker/.env.example."""
    root_env = Path(".env")
    example_env = Path("supabase/docker/.env.example")
    target_env = Path("supabase/docker/.env")

    if not example_env.exists():
        logger.warning(f"Supabase example env not found at {example_env}")
        return

    logger.info(f"Preparing Supabase environment at {target_env}")
    
    env_vars: Dict[str, str] = {}

    # 1. Load defaults from .env.example
    with open(example_env, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                env_vars[key] = value

    # 2. Override with values from root .env
    if root_env.exists():
        with open(root_env, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    else:
        logger.warning(f"Root {root_env} not found. Using defaults from example.")

    # 3. Write merged variables
    target_env.parent.mkdir(parents=True, exist_ok=True)
    with open(target_env, 'w') as f:
        f.write("# Generated by start_services.py - Merged configuration\n")
        f.write("# Defaults from supabase/docker/.env.example, overrides from root .env\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    logger.info(f"Successfully created {target_env}")

def generate_searxng_secret_key():
    """Generate a secret key for SearXNG using Python (cross-platform)."""
    settings_path = Path("searxng/settings.yml")
    settings_base_path = Path("searxng/settings-base.yml")

    if not settings_base_path.exists():
        logger.warning(f"SearXNG base settings not found at {settings_base_path}")
        return

    if not settings_path.exists():
        logger.info(f"Creating {settings_path} from {settings_base_path}")
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(settings_base_path, settings_path)

    with open(settings_path, 'r') as f:
        content = f.read()

    if 'ultrasecretkey' in content:
        logger.info("Generating secure SearXNG secret key...")
        new_key = secrets.token_hex(32)
        content = content.replace('ultrasecretkey', new_key)
        with open(settings_path, 'w') as f:
            f.write(content)
        logger.info("SearXNG secret key generated.")

def prepare_moltbot_env():
    """Ensure OPENCLAW_GATEWAY_TOKEN is set in the root .env."""
    root_env_path = Path(".env")
    token_key = "OPENCLAW_GATEWAY_TOKEN"

    if not root_env_path.exists():
        logger.info(f"Creating {root_env_path}...")
        root_env_path.touch()

    token_exists = False
    with open(root_env_path, 'r') as f:
        if f"{token_key}=" in f.read():
            token_exists = True

    if not token_exists:
        logger.info(f"Generating secure {token_key}...")
        new_token = secrets.token_hex(32)
        if set_key:
            set_key(str(root_env_path), token_key, new_token)
        else:
            with open(root_env_path, 'a') as f:
                f.write(f"\n{token_key}={new_token}\n")
        logger.info(f"Persisted {token_key} to {root_env_path}")

def check_searxng_permissions():
    """Check and modify docker-compose.yml for SearXNG first run permissions."""
    compose_path = Path("docker-compose.yml")
    if not compose_path.exists():
        return

    # Check for initialization file
    uwsgi_config = Path("searxng/uwsgi.ini")
    is_first_run = not uwsgi_config.exists()

    with open(compose_path, 'r') as f:
        content = f.read()

    target = "cap_drop:\n      - ALL"
    replacement = "# cap_drop:  # Temporarily disabled for first run\n      # - ALL"

    if is_first_run and target in content:
        logger.info("First run detected for SearXNG. Temporarily disabling cap_drop...")
        content = content.replace(target, replacement)
        with open(compose_path, 'w') as f:
            f.write(content)
    elif not is_first_run and replacement in content:
        logger.info("SearXNG initialized. Re-enabling cap_drop...")
        content = content.replace(replacement, target)
        with open(compose_path, 'w') as f:
            f.write(content)

def start_services(profile: str, environment: str):
    # 1. Start Supabase
    logger.info("Starting Supabase services...")
    supabase_cmd = ["docker", "compose", "-p", "localai", "-f", "supabase/docker/docker-compose.yml"]
    if environment == "public":
        supabase_cmd.extend(["-f", "docker-compose.override.public.supabase.yml"])
    supabase_cmd.extend(["up", "-d"])
    run_command(supabase_cmd)

    logger.info("Waiting for Supabase to initialize (10s)...")
    time.sleep(10)

    # 2. Start AI Services
    logger.info("Starting Local AI services...")
    ai_cmd = ["docker", "compose", "-p", "localai", "-f", "docker-compose.yml"]
    if profile and profile != "none":
        ai_cmd.extend(["--profile", profile])

    if environment == "private":
        ai_cmd.extend(["-f", "docker-compose.override.private.yml"])
    elif environment == "public":
        ai_cmd.extend(["-f", "docker-compose.override.public.yml"])

    ai_cmd.extend(["up", "-d"])
    run_command(ai_cmd)

def main():
    parser = argparse.ArgumentParser(description='Start the local AI and Supabase services.')
    parser.add_argument('--profile', choices=['cpu', 'gpu-nvidia', 'gpu-amd', 'none'], default='cpu',
                      help='Docker profile (default: cpu)')
    parser.add_argument('--environment', choices=['private', 'public'], default='private',
                      help='Environment type (default: private)')
    args = parser.parse_args()

    try:
        clone_supabase_repo()
        prepare_moltbot_env()
        generate_searxng_secret_key()
        prepare_supabase_env()
        check_searxng_permissions()

        logger.info("Stopping existing project containers...")
        down_cmd = ["docker", "compose", "-p", "localai", "-f", "docker-compose.yml"]
        if args.profile and args.profile != "none":
            down_cmd.extend(["--profile", args.profile])
        down_cmd.extend(["down"])
        run_command(down_cmd)

        start_services(args.profile, args.environment)

        logger.info("All services started successfully!")
    except Exception as e:
        logger.error(f"Failed to start services: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
